# Generated by Django 6.0 on 2025-12-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
